version: "3.9"
services:
  serverzadas:
    env_file:
      - vars_ambiente.conf
    command: npm run server
    build: ./build
    volumes:
      - ./build/ChatDemo/client:/ctf/client
      - ./build/ChatDemo/server:/ctf/server
      - ./build/ChatDemo/dist:/ctf/dist
    ports:
      - "6601:3001"
      - "3001:3001"
    networks:
      - redezadas
  clientzadas: 
    env_file:
      - vars_ambiente.conf
    command: npm run client
    volumes:
      - ./build/ChatDemo/client:/ctf/client
      - ./build/ChatDemo/server:/ctf/server
      - ./build/ChatDemo/dist:/ctf/dist
    build: ./build
    ports:
      - "6680:8080"
    networks:
      - redezadas
  botzadas:
    env_file:
      - vars_ambiente.conf
    command: /home/chromezadas/.nvm/versions/node/v16.13.0/bin/node example.js
    volumes:
      - ./chrome_decapitado:/ctf
    build: ./chrome_decapitado
    networks:
      - redezadas

networks:
  redezadas:
    name: custom_netzadas
