version: "3.9"
services:
  serverzadas:
    command: npm run server
    build: ./build
    volumes:
      - ./WebApp/client:/ctf/client
      - ./WebApp/server:/ctf/server
      - ./WebApp/dist:/ctf/dist
    ports:
      - "6601:3001"
  clientzadas:
    command: npm run client
    volumes:
      - ./WebApp/client:/ctf/client
      - ./WebApp/server:/ctf/server
      - ./WebApp/dist:/ctf/dist
    build: ./build
    ports:
      - "6680:8080"
  botzadas:
    command: node example.js
    volumes:
      - ./chrome_decapitado/example.js:/ctf/example.js
    build: ./chrome_decapitado
